import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import crypto from "crypto";

export async function POST(request: Request) {
  try {
    const url = new URL(request.url);
    const projectId = url.searchParams.get("projectId");
    
    if (!projectId) {
      return NextResponse.json({ error: "Missing projectId in query params" }, { status: 400 });
    }

    const payload = await request.text();
    const signature = request.headers.get("x-vercel-signature");

    // Initialize Supabase admin client
    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
    const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY! || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Find the project settings
    const { data: settings, error: settingsError } = await supabase
      .from("project_settings")
      .select("project_id, vercel_webhook_secret")
      .eq("project_id", projectId)
      .single();

    if (settingsError || !settings) {
      return NextResponse.json({ error: "Project settings not found" }, { status: 404 });
    }

    // Verify Vercel Webhook Signature if secret is configured
    if (settings.vercel_webhook_secret && signature) {
      const hmac = crypto.createHmac("sha1", settings.vercel_webhook_secret);
      const digest = hmac.update(payload).digest("hex");
      if (signature !== digest) {
        return NextResponse.json({ error: "Invalid signature" }, { status: 401 });
      }
    }

    let data;
    try {
      data = JSON.parse(payload);
    } catch {
      return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
    }

    // Only process successful deployments
    if (data.type !== "deployment.succeeded" && data.type !== "deployment.created") {
      return NextResponse.json({ message: "Ignored event type" }, { status: 200 });
    }

    const commitMessage = data.payload?.deployment?.meta?.githubCommitMessage || "New deployment triggered via Vercel";
    const commitAuthor = data.payload?.deployment?.meta?.githubCommitAuthorName || "Automated System";

    const aiGeneratedTitle = `New Vercel Deployment`;
    const aiGeneratedContent = `A new build was just deployed to Vercel by ${commitAuthor}.\n\n### Changes:\n- ${commitMessage}\n\n*Note: This draft was auto-generated by our AI based on Vercel webhook.*`;
    
    let type = "Improvement";
    if (commitMessage.toLowerCase().includes("fix")) type = "Fix";
    if (commitMessage.toLowerCase().includes("feat")) type = "New";

    // Insert draft release note
    const { error: insertError } = await supabase
      .from("release_notes")
      .insert({
        project_id: projectId,
        title: aiGeneratedTitle,
        content: aiGeneratedContent,
        type: type,
        status: "draft"
      });

    if (insertError) {
      console.error("Failed to insert drafted release:", insertError);
      return NextResponse.json({ error: "Failed to create draft" }, { status: 500 });
    }

    return NextResponse.json({ success: true, message: "Draft release created from Vercel deployment" }, { status: 200 });

  } catch (err) {
    console.error("Webhook error:", err);
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}
