import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import crypto from "crypto";

export async function POST(request: Request) {
  try {
    const payload = await request.text();
    const signature = request.headers.get("x-hub-signature-256");
    const event = request.headers.get("x-github-event");

    if (event !== "push") {
      return NextResponse.json({ message: "Ignoring non-push event" }, { status: 200 });
    }

    const data = JSON.parse(payload);
    const repoFullName = data.repository?.full_name; // e.g., "owner/repo"

    if (!repoFullName) {
      return NextResponse.json({ error: "Missing repository full_name" }, { status: 400 });
    }

    // Initialize Supabase admin client to search for the project
    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
    const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY! || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Find the project linked to this repo
    const { data: project, error: projectError } = await supabase
      .from("projects")
      .select("id, github_webhook_secret")
      .eq("github_repo", repoFullName)
      .single();

    if (projectError || !project) {
      console.log("No project found for repo:", repoFullName);
      return NextResponse.json({ error: "Repository not linked to any project" }, { status: 404 });
    }

    // Verify GitHub Webhook Signature
    if (project.github_webhook_secret && signature) {
      const hmac = crypto.createHmac("sha256", project.github_webhook_secret);
      const digest = "sha256=" + hmac.update(payload).digest("hex");
      if (signature !== digest) {
        return NextResponse.json({ error: "Invalid signature" }, { status: 401 });
      }
    }

    // Extract commits
    const commits = data.commits || [];
    if (commits.length === 0) {
      return NextResponse.json({ message: "No commits found in push" }, { status: 200 });
    }

    const commitMessages = commits.map((c: { message: string }) => c.message).join("\n");

    // --- MOCK AI DRAFTING ---
    // In reality, we would send `commitMessages` to OpenAI/Gemini
    // Prompt: "Translate these technical commit messages into a user-friendly release note."
    const aiGeneratedTitle = `Update: ${commits.length} new changes`;
    let aiGeneratedContent = `We've just pushed some new updates to improve your experience.\n\n### What's New:\n`;
    
    commits.forEach((c: { message: string }) => {
      aiGeneratedContent += `- ${c.message.split("\n")[0]}\n`;
    });
    
    aiGeneratedContent += `\n*Note: This draft was auto-generated by our AI based on recent GitHub commits.*`;
    
    let type = "Improvement";
    if (commitMessages.toLowerCase().includes("fix")) type = "Fix";
    if (commitMessages.toLowerCase().includes("feat")) type = "New";

    // Insert draft release note
    const { error: insertError } = await supabase
      .from("release_notes")
      .insert({
        project_id: project.id,
        title: aiGeneratedTitle,
        content: aiGeneratedContent,
        type: type,
        status: "draft"
      });

    if (insertError) {
      console.error("Failed to insert drafted release:", insertError);
      return NextResponse.json({ error: "Failed to create draft" }, { status: 500 });
    }

    return NextResponse.json({ success: true, message: "Draft release created from GitHub push" }, { status: 200 });

  } catch (err) {
    console.error("Webhook error:", err);
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}
