import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

export async function POST(request: Request) {
  try {
    const url = new URL(request.url);
    const projectId = url.searchParams.get("projectId");
    
    if (!projectId) {
      return NextResponse.json({ error: "Missing projectId in query params" }, { status: 400 });
    }

    const gitlabToken = request.headers.get("x-gitlab-token");
    const payload = await request.text();

    // Initialize Supabase admin client
    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
    const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY! || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Find the project settings
    const { data: settings, error: settingsError } = await supabase
      .from("project_settings")
      .select("project_id, gitlab_webhook_secret")
      .eq("project_id", projectId)
      .single();

    if (settingsError || !settings) {
      return NextResponse.json({ error: "Project settings not found" }, { status: 404 });
    }

    // Verify GitLab Token if secret is configured
    if (settings.gitlab_webhook_secret && gitlabToken !== settings.gitlab_webhook_secret) {
      return NextResponse.json({ error: "Invalid token" }, { status: 401 });
    }

    let data;
    try {
      data = JSON.parse(payload);
    } catch {
      return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
    }

    // Only process push events
    if (data.object_kind !== "push") {
      return NextResponse.json({ message: "Ignored non-push event" }, { status: 200 });
    }

    const commits = data.commits || [];
    if (commits.length === 0) {
      return NextResponse.json({ message: "No commits found in push" }, { status: 200 });
    }

    const commitMessages = commits.map((c: { message: string }) => c.message).join("\n");

    const aiGeneratedTitle = `Update: ${commits.length} new changes from GitLab`;
    let aiGeneratedContent = `We've just pushed some new updates.\n\n### What's New:\n`;
    
    commits.forEach((c: { message: string }) => {
      aiGeneratedContent += `- ${c.message.split("\n")[0]}\n`;
    });
    
    aiGeneratedContent += `\n*Note: This draft was auto-generated by our AI based on GitLab commits.*`;
    
    let type = "Improvement";
    if (commitMessages.toLowerCase().includes("fix")) type = "Fix";
    if (commitMessages.toLowerCase().includes("feat")) type = "New";

    // Insert draft release note
    const { error: insertError } = await supabase
      .from("release_notes")
      .insert({
        project_id: projectId,
        title: aiGeneratedTitle,
        content: aiGeneratedContent,
        type: type,
        status: "draft"
      });

    if (insertError) {
      console.error("Failed to insert drafted release:", insertError);
      return NextResponse.json({ error: "Failed to create draft" }, { status: 500 });
    }

    return NextResponse.json({ success: true, message: "Draft release created from GitLab push" }, { status: 200 });

  } catch (err) {
    console.error("Webhook error:", err);
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}
